eupgrade: set cached_only to false
libremesh/lime-packages pull request #1070
Opened 2024-01-25 09:36 UTC by selankon

Fixes #1069

2024-01-25 12:43 UTC, spiccinini commented
Did you try with the lime-app? Forcing no cache will slow the load of the app right @germanferrero ?

2024-01-29 08:54 UTC, selankon commented
@spiccinini the react query that check for updates should not block the ui. 

BTW, we could use a background process or something like that, to check the updates, and let this just set to false? I am not familiarized with OWRT systems, have they something similar to services?

2024-02-05 17:52 UTC, G10h4ck requested changes

2024-02-05 17:52 UTC, G10h4ck commented on packages/eupgrade/files/usr/libexec/rpcd/eupgrade
> +end
missing new line at the end of file

2024-02-05 17:55 UTC, G10h4ck commented
I would expect from a function named like that to not return a cached result.
Do the sub-called function trigger the download?
If this change slow down the UI, I would suggest to split triggering the download into another function

2024-02-05 18:48 UTC, spiccinini commented
> Do the sub-called function trigger the download?

AFAIK no. The issue is that until the http GET does not return it will block (and if you don't have internet it will timeout in more than a few seconds).

2024-02-05 18:50 UTC, spiccinini commented
> @spiccinini the react query that check for updates should not block the ui.

You mean that the current code does not block or that it should not? In some version of the  lime-app it blocked the main page of the app, if you tested something like even adding a sleep(30) in the lua file does not block then good!.

2024-04-03 08:20 UTC, ilario commented
This edit has been included by @selankon in #1101 so I would close this pull request.
If you consider that the discussion was not finished and that the change should be reverted, please re-open this or open a new issue.

2024-04-03 08:20 UTC, closed without merging