Adding the random-numgen command and use it for removing usage of $RANDOM
libremesh/lime-packages pull request #991
Opened 2023-03-27 14:07 UTC by ilario

Fix #800 
Replaces the (other half of) #980 

When https://github.com/openwrt/packages/pull/20728 will be included in openwrt-22.03, the package will need to be removed from lime-packages repository.

2023-03-28 15:15 UTC, G10h4ck commented
You forgot to add the dependency on `random-numgen` for packages that used `$RANDOM` before

2023-03-28 15:15 UTC, G10h4ck requested changes
see discussion

2023-03-29 17:00 UTC, ilario commented
Right! Thanks!
Fixing ASAP.

2023-03-30 10:46 UTC, ilario commented
Now it should be good.

2023-04-08 17:15 UTC, pony1k commented
Why do we not want to use the busybox-`$RANDOM`? We would only need to add a dependency on `BUSYBOX_CUSTOM`.

2023-04-08 21:50 UTC, ilario commented
> Why do we not want to use the busybox-`$RANDOM`? We would only need to add a dependency on `BUSYBOX_CUSTOM`.

For going toward the solution of #1000

2023-04-14 09:03 UTC, G10h4ck approved these changes

2023-04-14 09:03 UTC, merged

2023-04-27 09:38 UTC, G10h4ck commented
Bufff, so we should just revert this PR -_-

2023-04-27 09:39 UTC, G10h4ck commented
@ilario can you revert it cleanly ?

2023-04-27 09:54 UTC, ilario commented
I would wait for reverting it.
This can coexist with $RANDOM.
I would revert it once we abandon the support for OpenWrt 22.03 (that will happen in a long time, as we just dropped the support for OpenWrt 19.07...).

2023-04-27 10:32 UTC, G10h4ck commented
My modifications are targetting openwrt main branch not 2020 release

2023-04-27 10:54 UTC, ilario commented
2020.3 release does not include this.
2023.1 will be based on OpenWrt 22.03, for which the $RANDOM-inclusion commit will, very likely, not be backported. So we need random-numgen.

Anyway, there is very little harm (maybe the image size increases by 1 kB? I did not measure) in keeping random-numgen until when we are sure that everybody is compiling on an OpenWrt version that includes $RANDOM.